#pipeline > stages > jobs  > steps/tasks

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: stage1
  jobs:
  - job: job1
    steps:
    - script: echo Hello, world!
    - script: |
        echo Building yml script.
        echo See https://aka.ms/yaml
 
 