# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Pipelines > Stages > Jobs > Tasks(Steps)

jobs:
- job: Job1
  steps:
  - script: echo Job1 - Hello, world, changed!
    displayName: 'Running a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      echo more information
    displayName: 'Running a multi-line script'
- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Job2!
    displayName: 'Running a one-line script'
- job: Job3
  dependsOn: Job1
  steps:
  - script: echo Job3!
    displayName: 'Running a one-line script'
- job: Job4
  dependsOn: 
  - Job2
  - Job3
  steps:
  - script: echo Job3!
    displayName: 'Running a one-line script'
