
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: DevDeploy
  jobs:
  - job: job1
    steps:
    - bash: echo $(Agent.BuildDirectory)
    - bash: echo $(Agent.Name)
    - bash: echo $(Agent.OS)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo $(Build.StagingDirectory)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(System.StageName)
    - bash: echo $(firstvar)
