trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Pipelines > Stages > Jobs > Tasks(Steps)

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob
- stage: Dev
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeployJob
- stage: QA
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob
- stage: Prod
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeployJob